spring.application.name=snapconnect-backend

spring.datasource.url=jdbc:mysql://localhost:3306/snapconnect?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root.1/root.2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080